/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as NavigationLayoutImport } from './routes/NavigationLayout'
import { Route as aboutAboutImport } from './routes/about/about'
import { Route as homeHomeImport } from './routes/home/home'

// Create/Update Routes

const NavigationLayoutRoute = NavigationLayoutImport.update({
  id: '/_NavigationLayout',
  getParentRoute: () => rootRoute,
} as any)

const aboutAboutRoute = aboutAboutImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => NavigationLayoutRoute,
} as any)

const homeHomeRoute = homeHomeImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => NavigationLayoutRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_NavigationLayout': {
      id: '/_NavigationLayout'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof NavigationLayoutImport
      parentRoute: typeof rootRoute
    }
    '/_NavigationLayout/': {
      id: '/_NavigationLayout/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof homeHomeImport
      parentRoute: typeof NavigationLayoutImport
    }
    '/_NavigationLayout/about': {
      id: '/_NavigationLayout/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof aboutAboutImport
      parentRoute: typeof NavigationLayoutImport
    }
  }
}

// Create and export the route tree

interface NavigationLayoutRouteChildren {
  homeHomeRoute: typeof homeHomeRoute
  aboutAboutRoute: typeof aboutAboutRoute
}

const NavigationLayoutRouteChildren: NavigationLayoutRouteChildren = {
  homeHomeRoute: homeHomeRoute,
  aboutAboutRoute: aboutAboutRoute,
}

const NavigationLayoutRouteWithChildren =
  NavigationLayoutRoute._addFileChildren(NavigationLayoutRouteChildren)

export interface FileRoutesByFullPath {
  '': typeof NavigationLayoutRouteWithChildren
  '/': typeof homeHomeRoute
  '/about': typeof aboutAboutRoute
}

export interface FileRoutesByTo {
  '/': typeof homeHomeRoute
  '/about': typeof aboutAboutRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_NavigationLayout': typeof NavigationLayoutRouteWithChildren
  '/_NavigationLayout/': typeof homeHomeRoute
  '/_NavigationLayout/about': typeof aboutAboutRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '' | '/' | '/about'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/about'
  id:
    | '__root__'
    | '/_NavigationLayout'
    | '/_NavigationLayout/'
    | '/_NavigationLayout/about'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  NavigationLayoutRoute: typeof NavigationLayoutRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  NavigationLayoutRoute: NavigationLayoutRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/_NavigationLayout"
      ]
    },
    "/_NavigationLayout": {
      "filePath": "NavigationLayout.tsx",
      "children": [
        "/_NavigationLayout/",
        "/_NavigationLayout/about"
      ]
    },
    "/_NavigationLayout/": {
      "filePath": "home/home.tsx",
      "parent": "/_NavigationLayout"
    },
    "/_NavigationLayout/about": {
      "filePath": "about/about.tsx",
      "parent": "/_NavigationLayout"
    }
  }
}
ROUTE_MANIFEST_END */
