/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as homeHomeImport } from './routes/home/home'

// Create/Update Routes

const homeHomeRoute = homeHomeImport.update({
  id: '/test',
  path: '/test',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/test': {
      id: '/test'
      path: '/test'
      fullPath: '/test'
      preLoaderRoute: typeof homeHomeImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/test': typeof homeHomeRoute
}

export interface FileRoutesByTo {
  '/test': typeof homeHomeRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/test': typeof homeHomeRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/test'
  fileRoutesByTo: FileRoutesByTo
  to: '/test'
  id: '__root__' | '/test'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  homeHomeRoute: typeof homeHomeRoute
}

const rootRouteChildren: RootRouteChildren = {
  homeHomeRoute: homeHomeRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/test"
      ]
    },
    "/test": {
      "filePath": "home/home.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
